### PR TITLE
lobby

### PR DESCRIPTION
**Pull request by miaoxudong111**

### CODE REVIEW

**Comment by farfar336** [comment]
Looks good. I have a couple comments:

1.
image
I suggest changing the alert message to "You can't enter this chat as it is not approved yet"

2.
image

This one did not seem to work for me. Here are my friends:

image

Here is what is displayed when I try to create a chat:
image


For users, it should display 2(me), 11111(friend), 3(friend), 4(friend). For moderators, it should display all moderators, not just the ones in the my friends.

**Comment by farfar336** [comment]
Thanks for making the changes! It is working as intended now:

1.
image

2.
image

I approve of merging this

**Review by SaraK207 — CHANGES_REQUESTED** [review]
In the create chat screen, some moderators are being listed twice. This is because we are getting users and mods that are friends but then we are also retrieving all mods in the app to list in the mods section. So some mods who are friends are being retrieved twice. My suggestion is that mods should also be a friend to appear in the create new chat screen. So we can simply remove the  "user.find({type:"Moderator"},function(err, allmoderator){}" section on line 147 of server.js.

Another suggestion: I think mods should be able to enter chat even if it's not approved yet. This way the mods can check out who are the participants before approving it.

**Comment by farfar336** [comment]
> In the create chat screen, some moderators are being listed twice. This is because we are getting users and mods that are friends but then we are also retrieving all mods in the app to list in the mods section. So some mods who are friends are being retrieved twice. My suggestion is that mods should also be a friend to appear in the create new chat screen. So we can simply remove the "user.find({type:"Moderator"},function(err, allmoderator){}" section on line 147 of server.js.

I didn't encounter this scenario:
image

2 is a moderator who is in my friends list. 2 does not appear twice. I am running this code after Xudong's latest commit, so maybe it's fixed now? Or maybe I am misunderstanding the scenario?

> Another suggestion: I think mods should be able to enter chat even if it's not approved yet. This way the mods can check out who are the participants before approving it.

What would be the purpose of checking out who the participants are?

**Review by farfar336 — CHANGES_REQUESTED** [review]
I found a major issue:

image

I am user 5, but I am not displayed in the users list, so I can't select myself as a participant to create a chat. But, I think we should leave it like this, and instead, when a user creates a new chat, they are automatically selected as a participant. So, there would be no need to display the user on the users list

Before we implement this, I'd like to ask Sara's opinion on this.

**Comment by SaraK207** [comment]
> > In the create chat screen, some moderators are being listed twice. This is because we are getting users and mods that are friends but then we are also retrieving all mods in the app to list in the mods section. So some mods who are friends are being retrieved twice. My suggestion is that mods should also be a friend to appear in the create new chat screen. So we can simply remove the "user.find({type:"Moderator"},function(err, allmoderator){}" section on line 147 of server.js.
> 
> I didn't encounter this scenario:
> image
> 
> 2 is a moderator who is in my friends list. 2 does not appear twice. I am running this code after Xudong's latest commit, so maybe it's fixed now? Or maybe I am misunderstanding the scenario?
> 
Yeah Xudong fixed the duplication problem already
> > Another suggestion: I think mods should be able to enter chat even if it's not approved yet. This way the mods can check out who are the participants before approving it.
> 
> What would be the purpose of checking out who the participants are?

Before approving the chat the mod might want to see who is involved in the chat. This is a minor detail and it doesn't matter too much since the mod has the ability to remove the chat even after approving it. So we can just ignore this.

**Comment by SaraK207** [comment]
> I found a major issue:
> 
> image
> 
> I am user 5, but I am not displayed in the users list, so I can't select myself as a participant to create a chat. But, I think we should leave it like this, and instead, when a user creates a new chat, they are automatically selected as a participant. So, there would be no need to display the user on the users list
>
But you are displayed on the right in the mods list. Since you are a mod, you will be listed in the mods list. However, the change we can make is that a mod should be able to make a chat without a user but users must have at least one mod. 
> Before we implement this, I'd like to ask Sara's opinion on this.

**Comment by farfar336** [comment]
> > > In the create chat screen, some moderators are being listed twice. This is because we are getting users and mods that are friends but then we are also retrieving all mods in the app to list in the mods section. So some mods who are friends are being retrieved twice. My suggestion is that mods should also be a friend to appear in the create new chat screen. So we can simply remove the "user.find({type:"Moderator"},function(err, allmoderator){}" section on line 147 of server.js.
> > 
> > 
> > I didn't encounter this scenario:
> > image
> > 2 is a moderator who is in my friends list. 2 does not appear twice. I am running this code after Xudong's latest commit, so maybe it's fixed now? Or maybe I am misunderstanding the scenario?
> 
> Yeah Xudong fixed the duplication problem already
> 
> > > Another suggestion: I think mods should be able to enter chat even if it's not approved yet. This way the mods can check out who are the participants before approving it.
> > 
> > 
> > What would be the purpose of checking out who the participants are?
> 
> Before approving the chat the mod might want to see who is involved in the chat. This is a minor detail and it doesn't matter too much since the mod has the ability to remove the chat even after approving it. So we can just ignore this.

Sounds good

**Comment by farfar336** [comment]
> > I found a major issue:
> > image
> > I am user 5, but I am not displayed in the users list, so I can't select myself as a participant to create a chat. But, I think we should leave it like this, and instead, when a user creates a new chat, they are automatically selected as a participant. So, there would be no need to display the user on the users list
> 
> But you are displayed on the right in the mods list. Since you are a mod, you will be listed in the mods list. 

My mistake, you are right, it's working as intended. 

>However, the change we can make is that a mod should be able to make a chat without a user but users must have at least one mod.

That's a good idea.

What's your opinion on the user automatically being selected to be added to the chat, without them needing to select themselves?

**Comment by SaraK207** [comment]
> > > I found a major issue:
> > > image
> > > I am user 5, but I am not displayed in the users list, so I can't select myself as a participant to create a chat. But, I think we should leave it like this, and instead, when a user creates a new chat, they are automatically selected as a participant. So, there would be no need to display the user on the users list
> > 
> > 
> > But you are displayed on the right in the mods list. Since you are a mod, you will be listed in the mods list.
> 
> My mistake, you are right, it's working as intended.
> 
> > However, the change we can make is that a mod should be able to make a chat without a user but users must have at least one mod.
> 
> That's a good idea.
> 
> What's your opinion on the user automatically being selected to be added to the chat, without them needing to select themselves?

I think that's a good idea and makes it more intuitive.
Another point: The mods list is currently listing all mods in the application. Should we also show only mods who are friends?

**Comment by farfar336** [comment]
> Another point: The mods list is currently listing all mods in the application. Should we also show only mods who are friends?

That's a good idea too.

**Comment by farfar336** [comment]
Summary of suggested changes:
-Only moderators that are friends with the user are displayed when creating a chat
-Users are automatically selected to be added to the chat, without them needing to select themselves when creating a chat
-A moderator should be able to make a chat without a user but users still must have at least one moderator to create a chat

**Review by SaraK207 — APPROVED** [review]
The restricted words list is working well! The only this is that I had to create the collection manually so I've written some code that will check whether the collection exists, if not then it creates the collection. Then it checks whether there is an entry in the collection and creates that if needed. So just copy/paste this code on line 25 of server.js and push these changes to your branch: 
```
db.once('open', _ => {
  console.log('Database connected:', url)
  //Copy the part below
  mongoose.connection.db.listCollections({name: 'restrictedWords'})
    .next(function(err, collinfo) {
        if (collinfo) {
            console.log("restrictedWords collection exists")
        }
        else{
          db.createCollection("restrictedWords");
        }
    });
  
  db.collection("restrictedWords").findOne({}, function(error, result) {
    if (error) console.log(error);
    else{
      if(result === null){
        db.collection("restrictedWords").insertOne({name:"word", Words: []}, function(err, res) {
          if (err) console.log(err);
          console.log("Restricted Words list created");
        });
      }
    }
    
  });
})
```
I think we should merge this branch now. The other lobby changes can be done later.

**Comment by farfar336** [comment]
I am assuming the recent commit was for the implementation for the restricted word list. If that is the case, then I have a few comments:

image

1. The fake word list is still present:
image

2. When I run the code, click "Bad Words", I get this error:
image

> The other lobby changes can be done later.

Sounds good

**Comment by SaraK207** [comment]
> I am assuming the recent commit was for the implementation for the restricted word list. If that is the case, then I have a few comments:
> 
> image
> 
> 1. The fake word list is still present:
>    image
> 2. When I run the code, click "Bad Words", I get this error:
>    image
> 
> > The other lobby changes can be done later.
> 
> Sounds good

**Comment by SaraK207** [comment]
> I am assuming the recent commit was for the implementation for the restricted word list. If that is the case, then I have a few comments:
> 
> image
> 
> 1. The fake word list is still present:
>    image
> 2. When I run the code, click "Bad Words", I get this error:
>    image
> 
> > The other lobby changes can be done later.
> 
> Sounds good

I think you didn't have the database collection setup properly. Xudong has pushed the code snippet I provided which will automatically set up the database for you. So before testing again remove any restrictedWords collection from your database and simply run this code again.

**Comment by farfar336** [comment]
> remove any restrictedWords collection

I don't think I have any restrictedWords collection at the moment, do I? Here is what I see on MongoDB

image

**Comment by SaraK207** [comment]
> > remove any restrictedWords collection
> 
> I don't think I have any restrictedWords collection at the moment, do I? Here is what I see on MongoDB
> 
> image

That's perfect now run the most recent version of the branch and it should work now.

**Comment by farfar336** [comment]
It is working now. I have a few suggestions:

1. I have the ability to add a blank (''):

image

This is added by leaving the field blank. I suggest not allowing this.

2. When the user enters a word that is already in the list, this alert is displayed:
image

From a user perspective, database is a technical term, so I would suggest changing this alert message to something less technical, like "The word is already in the list"

**Comment by farfar336** [comment]
The above suggestions have been implemented. 

I encountered another issue. I am able to enter multiple entries of the same word:

image

I suggest changing it so that multiple entries of the same word cannot be entered

**Comment by farfar336** [comment]
The above suggestion has been implemented. I approve of merging this. But, I'd like Sara to check the updated version of this first.

**Comment by SaraK207** [comment]
Everything seems to be working as intended. I approve of merging this branch.

**Review by SaraK207 — APPROVED** [review]
Everything seems to be working as intended. I approve of merging this branch,

**Review by farfar336 — APPROVED** [review]

**Pull request merged**
