### PR TITLE
Chat Backend Part 2

### PR DESCRIPTION
**Pull request by liconway**
https://trello.com/c/tS3obbNm/10-chat-screen

### CODE REVIEW

**Comment by farfar336** [comment]
Looks good! It is working as intended. I approve of merging this

**Review by SaraK207 — APPROVED** [review]
Looks good to me as well. I approve this for merging.

There is a slight issue in the lobby I wanted to point out. When a chat is approved/rejected or when the user is added to a new chat or removed from the new chat, the lobby is not immediately showing the results. However, the changes do show up when I go to homepage and come back so I think we just have to refresh the lobby anytime the above actions occur.

**Comment by farfar336** [comment]
> When a chat is approved/rejected or when the user is added to a new chat or removed from the new chat, the lobby is not immediately showing the results.

What do you mean by "Immediately"?

**Comment by SaraK207** [comment]
> > When a chat is approved/rejected or when the user is added to a new chat or removed from the new chat, the lobby is not immediately showing the results.
> 
> What do you mean by "Immediately"

Open two windows and log in as two different users. Then make one user enter a chat and have the other user in the lobby. If the first user kicks the second user from the chat then the chat should disappear from the second user's lobby. However this doesn't happen and the chat remains in the list. Only when the second user leaves the lobby then comes back to it do they see that the chat is gone from their lobby.

**Comment by SaraK207** [comment]
I have pushed changes to the branch that provide real-time updates to the lobbies of all connected users. There are now no more issues in this branch so it can be merged.

**Comment by farfar336** [comment]
> Open two windows and log in as two different users. Then make one user enter a chat and have the other user in the lobby. If the first user kicks the second user from the chat then the chat should disappear from the second user's lobby. However this doesn't happen and the chat remains in the list. Only when the second user leaves the lobby then comes back to it do they see that the chat is gone from their lobby.

Oh, that makes sense. I noticed the same thing with approving chats. So, if a mod approves a chat while the user is waiting in the lobby, the user has to go to the home page and come back to the lobby to see that the chat has been approved. The update won't happen if the user waits in the lobby. Should we fix this too?

> I have pushed changes to the branch that provide real-time updates to the lobbies of all connected users. There are now no more issues in this branch so it can be merged.

Thanks for doing that. It seems to be working on my end as well.

**Review by farfar336 — APPROVED** [review]

**Pull request merged**
