### PR TITLE
Chat Backend & Message Collection

### PR DESCRIPTION
**Pull request by liconway**
Sending and receiving messages to chat rooms

Note that each list item has `user-name-<name>` and `user-type-<type>` (e.g. Moderator) for easier CSS down the line

### CODE REVIEW

**Comment by farfar336** [comment]
Looks good! All the tasks here are complete:

image

The only thing that I suggest changing is making the latest message display at the bottom

**Comment by liam-prod** [comment]
The latest messages are at the bottom of the DOM, but the display is reversed. You'll notice that issue also exists before this PR

See #31

**Review by SaraK207 — APPROVED** [review]
Looks good. Everything works well. The only thing is that messages are not being sent in the right order but I know a way to fix this. I approve of merging this branch.

**Review by farfar336 — APPROVED** [review]
Sara mentioned she knows a way to fix the ordering of the messages displayed, so we can merge this.

**Pull request merged**
