### PR TITLE
Add Profile Screen Backend

### PR DESCRIPTION
**Pull request by liconway**
https://trello.com/c/oPnpjn5C

image

### CODE REVIEW

**Comment by farfar336** [comment]
Looks good. Thanks for providing a screenshot!

I have a comment:

Here are the friends I have added:

image

When I try to view the profile of "2" from the friends screen, I see this:

image

I would expect to see "Display Name: 2" and "Account Type: Moderator", but that's not what is shown above. Is this expected?

**Comment by liam-prod** [comment]
It's expected, the Trello mentioned nothing about implementing friend profiles. This can be added if needed.

**Comment by SaraK207** [comment]
> It's expected, the Trello mentioned nothing about implementing friend profiles.

Yup this is my task which I will complete shortly @farfar336

**Review by SaraK207 — APPROVED** [review]
Everything is working as intended. I approve of merging this branch.

**Comment by farfar336** [comment]
Oh okay, in that case, I approve of merging this as well. I will merge this now.

**Pull request merged**
