### PR TITLE
Chat backend part1 and additional updates

### PR DESCRIPTION
**Pull request by SaraK207**
### The following updates are in this branch:
**Main Changes**

- For list of users, display normal users in black color and moderator names in green

- Show which user is "you" in the users list. This can be indicated with a "(You)" beside their display name.

- Display messages from users as black and messages from moderators as green

- Button for "View Profile" directs screen to the selected user (this currently takes user to the profile page Liam has not completed  the backend for profile so it does not display the user's info yet).

- When a message is sent, if it contains any word from the restricted word list, that message does not get sent and does not get stored in the server messages. 

- An alert prompt for the above saying "The message contains a bad word and was not sent"

**Additional Changes**

- Chat screen was still not displaying messages in the right order. Messages were aligned to the top instead of bottom. This has now been fixed.

- Added code to make chat screen automatically scroll to the bottom anytime a new chat message arrives.

- Added emoji functionality to chat screen for the three emojis required from A3

- In chat screen users list, added code to restrict selection of users to only one user at a time. This was implemented because it did not make sense to have multiple users selected and then click "view profile" button

- There were 2 click event handlers in 2 different files for the the #enterChatButton. This was allowing users to enter unapproved chats. There is now only one handler and users can enter chats only if they have been approved.

- Ensured the user's socket was leaving the current chat anytime a 'home' or 'logout' button is clicked. This prevents user from being connected to multiple chats and messages being sent to the wrong chats.

- In the create chat lists the mods and users will only be listed if they are a friend

- The create chat screen automatically selects current user and does not display them in the lists

- Create chat screen requires that user select at least one other person to participate in the chat. Users cannot have a chat with just themselves.

- Create chat screen: Mods are able to create chats without any users. This allows Mod only chats.

- Create chat screen: Users must select at least one mod but are not required to choose other users. 

- Removed unnecessary console.log statements

- Small UI changes in bad words screen

### CODE REVIEW

**Comment by farfar336** [comment]
Thanks for listing down the changes as well as dividing the main changes from the additional changes. 

I have a few comments:

1.
> An alert prompt for the above saying "The message contains a bad word and was not sent"

Here is the actual alert message:

image

I would suggest changing this to "The message contains a bad word and was not sent". The reason for this is:
-We changed the label of "Restricted Words" to "Bad Words". This was because "Bad" is more understood by kids than "Restricted"
-The user should know what happened to their message. So, by stating that it was not sent, they are informed of that

2. The "Bad Words" filter is working in a particular way. Here is what I have in the list:

image

Notice "12" is in there. When I try to type in "4123" in the chat, it says it is in the word list:
image

I'm okay with leaving it as it is, I just wanted to bring this to our attention in case someone else suggests to change it

I approve of the additional changes. There was a lot, so thanks for doing that!

**Review by farfar336 — CHANGES_REQUESTED** [review]
.

**Comment by SaraK207** [comment]
> Thanks for listing down the changes as well as dividing the main changes from the additional changes.
> 
> I have a few comments:
> 
> 
> > An alert prompt for the above saying "The message contains a bad word and was not sent"
> 
> Here is the actual alert message:
> 
> image
> 
> I would suggest changing this to "The message contains a bad word and was not sent". The reason for this is:
> -We changed the label of "Restricted Words" to "Bad Words". This was because "Bad" is more understood by kids than "Restricted"
> -The user should know what happened to their message. So, by stating that it was not sent, they are informed of that
> 
I have updated this.
> 1. The "Bad Words" filter is working in a particular way. Here is what I have in the list:
> 
> image
> 
> Notice "12" is in there. When I try to type in "4123" in the chat, it says it is in the word list:
> image
> 
> I'm okay with leaving it as it is, I just wanted to bring this to our attention in case someone else suggests to change it
> 
Yeah this behaviour was unintentional but I decided to leave it because it makes the filtering more robust. For example, the kids could have found a loophole and just sent bad words like $badWord$ so it would get sent because the word in the list does not contain the dollar signs. However, with the current system, users can't embed the bad words between other characters. We can change this though if someone doesn't like this method.

Also just as an additional point, parents can technically also block links by entering the url in the bad words list. For example if a parent wants to prevent kids from sending links to facebook they could just put www.facebook.com in the list and any messages containing any sort of link to facebook will get blocked. So given this, we could possibly change the 'bad words' list to be bad words and links' if it makes sense.
> I approve of the additional changes. There was a lot, so thanks for doing that!

**Comment by farfar336** [comment]
> I have updated this.
I just checked and it is indeed implemented: 
image

> We can change this though if someone doesn't like this method.

We'll keep it for now. If someone wants to change it in the future, we can do that.

> So given this, we could possibly change the 'bad words' list to be bad words and links' if it makes sense.

That's a good idea. If we are to do this, I think it would be better if we the links had it's own page, because mixing in links with words is messy, from a practical perspective. I don't think it would be hard to implement, as we could just copy and paste 90% of the code for the "Bad Words' code. What do you think?

**Comment by SaraK207** [comment]
> > I have updated this.
> > I just checked and it is indeed implemented:
> > image
> 
> > We can change this though if someone doesn't like this method.
> 
> We'll keep it for now. If someone wants to change it in the future, we can do that.
> 
> > So given this, we could possibly change the 'bad words' list to be bad words and links' if it makes sense.
> 
> That's a good idea. If we are to do this, I think it would be better if we the links had it's own page, because mixing in links with words is messy, from a practical perspective. I don't think it would be hard to implement, as we could just copy and paste 90% of the code for the "Bad Words' code. What do you think?

Yeah it will be pretty easy to implement this. In the database we can simply add a new array under the words array called links and store it in there. Rest of the code will be the same as the bad words.

**Comment by farfar336** [comment]
> Yeah it will be pretty easy to implement this. In the database we can simply add a new array under the words array called links and store it in there. Rest of the code will be the same as the bad words.

Sounds good. Since you're the most familiar with this, I think it would take you the least amount of time out of anyone else to do this. Would you be okay to implement this?

**Comment by SaraK207** [comment]
> > Yeah it will be pretty easy to implement this. In the database we can simply add a new array under the words array called links and store it in there. Rest of the code will be the same as the bad words.
> 
> Sounds good. Would you be okay to implement this?

Yeah I'll have it done by tomorrow. Should I implement the changes in this branch?

**Comment by farfar336** [comment]
> Yeah I'll have it done by tomorrow. Should I implement the changes in this branch?

It's preferred if we merge this first, and then make a new branch for it. Is that okay with you?

Also, are you okay with labeling it as  "Bad Links", which is similar to "Bad Words"?

**Comment by SaraK207** [comment]
> > Yeah I'll have it done by tomorrow. Should I implement the changes in this branch?
> 
> It's preferred if we merge this first, and then make a new branch for it. Is that okay with you?
> 
Sure I will create a new branch.
> Also, are you okay with labeling it as "Bad Links", which is similar to "Bad Words"?

Yeah I will make sure it's consistent with Bad Words

**Comment by farfar336** [comment]
Sounds good, I will merge this branch then.

**Review by farfar336 — APPROVED** [review]

**Pull request merged**
