### PR TITLE
Farrukh/chat screen frontend

### PR DESCRIPTION
**Pull request by farfar336**
Moderator view:

image

User view:
image

One issue is that on the button, the "View Profile" text appears outside of the button. I have attempted to fix this for 30 minutes and was not able to find a solution. Feel free to let me know if you know how to fix this

### CODE REVIEW

**Comment by SaraK207** [comment]
> Moderator view:
> 
> image
> 
> User view:
> image
> 
> One issue is that on the button, the "View Profile" text appears outside of the button. I have attempted to fix this for 30 minutes and was not able to find a solution. Feel free to let me know if you know how to fix this

I think just using CSS to change the size for #chatViewProfileButton will work. I tried it in inspect element and it worked.

I have another suggestion for add user (a rough mockup):
addUser

Also the chats are not aligned at the bottom. Chats should start at the bottom and every new chat should push the previous one up and the new chat should sit aligned at the very bottom.

**Comment by farfar336** [comment]
> I think just using CSS to change the size for #chatViewProfileButton will work. I tried it in inspect element and it worked.

I'll give that a try, thanks!



> Also the chats are not aligned at the bottom. Chats should start at the bottom and every new chat should push the previous one up and the new chat should sit aligned at the very bottom.

This branch was created before I merged Liam's branch to master. So, once I merge this to the master branch, it should be fixed.

**Comment by farfar336** [comment]
Updated UI for User:

image

Moderator:
image

**Comment by farfar336** [comment]
Centered the add user button:
image

**Review by SaraK207 — APPROVED** [review]
I approve this for merging

**Pull request merged**
