### PR TITLE
Package Rework

### PR DESCRIPTION
**Pull request by liconway**
A couple things:
1) `node_modules` is messy in Git, and is generally not recommended. Especially since some modules are OS-dependent. So this removes the directory and places it in the `.gitignore` file.
2) Since `node_modules` was removed, I added a note to the README file about `npm ci`
3) I added `dotenv` and `nodemon` packages for easier development
    * dotenv because I couldn't use the default DB settings
    * nodemon just restarts the app whenever code changes are made, it's a convenience tool
    * Note that both of these tools can be invisible, and nothing changes if you have no intention/no knowledge of using them. The only difference is `npm ci` or equivalent will need to be run once to install dotenv.

### CODE REVIEW

**Comment by farfar336** [comment]
> 1. `node_modules` is messy in Git, and is generally not recommended. Especially since some modules are OS-dependent. So this removes the directory and places it in the `.gitignore` file.

I've read this online as well. Do you suggest we remove it?

> dotenv because I couldn't use the default DB settings

Does this mean you weren't able to use MongoDB?

**Comment by liam-prod** [comment]
> I've read this online as well. Do you suggest we remove it?

It'd be helpful IMO.

> Does this mean you weren't able to use MongoDB?

I'm able to use MongoDB, I'm not able to use port 27017

**Comment by SaraK207** [comment]
So if we integrate these changes then all we have to do is just run npm ci once and then run our server like normal right?

**Comment by farfar336** [comment]
> > I've read this online as well. Do you suggest we remove it?
> 
> It'd be helpful IMO.

In that case, let's remove it. You seem to be knowledgeable about this stuff more than me. Would you be able to remove it?

> > Does this mean you weren't able to use MongoDB?
> 
> I'm able to use MongoDB, I'm not able to use port 27017

Oh okay. I don't know much about this, maybe Sara can share her thoughts on this

**Review by farfar336 — APPROVED** [review]

**Comment by SaraK207** [comment]
> > > I've read this online as well. Do you suggest we remove it?
> > 
> > 
> > It'd be helpful IMO.
> 
> In that case, let's remove it. You seem to be knowledgeable about this stuff more than me. Would you be able to remove it?
> 
> > > Does this mean you weren't able to use MongoDB?
> > 
> > 
> > I'm able to use MongoDB, I'm not able to use port 27017
> 
> Oh okay. I don't know much about this, maybe Sara can share her thoughts on this

Port 27017 is the default port on which the MongoDB server runs. Anyway I'm ok with merging this as it has useful features and the application is still running normally.

**Review by SaraK207 — APPROVED** [review]

**Pull request merged**
