### PR TITLE
Bad Links list, message filtering, minor updates to login/register

### PR DESCRIPTION
**Pull request by SaraK207**
**Main Updates**

- New collection in database will store both bad words and links

- Home page: created button for bad links

- Created bad links page and all required functionality

- Chat will now check for both bad words and links

**Additional Updates**

- Home page: created a new row for the bad words/links buttons

- For the login/registration pages, user emails were case-sensitive. This means one user could make an account with email "myemail@gmail.com" and a different user could make an account with email "MYEMAIL@gmail.com". Since emails are not supposed to be case sensitive, code was added to convert the email input for login/register to lowercase before storing in database or login validation.

- Added functionality to suspend user accounts. When user tries to login, a check will be done to see if the account is approved or not. The admins of the application(us) can go into mongoDB Compass and change a user's approved field to 'false' to suspend their account. When a suspended user tries to login, they will get an alert message and will not be able to access their account.

- Updated comments in various files

- Removed unnecessary or commented-out code in various files

### CODE REVIEW

**Comment by farfar336** [comment]
Looks good. I have a few comments:

1.
image

Suggestion: Would it be possible to distinguish a bad link and a bad word and have that reflected in the alert message? For example, if I type in a bad word, it would say "This message contains a bad word and was not sent", and if I type a bad link, it would say "This message contains a bad link and was not sent"? If it's possible, but takes longer than 5 minutes to implement, then there is no need to do this.

2. 
>For the login/registration pages, user emails were case-sensitive. This means one user could make an account with email "myemail@gmail.com" and a different user could make an account with email "MYEMAIL@gmail.com". Since emails are not supposed to be case sensitive, code was added to convert the email input for login/register to lowercase before storing in database or login validation.

Comment: That's a good idea.

3.
> Added functionality to suspend user accounts. When user tries to login, a check will be done to see if the account is approved or not. The admins of the application(us) can go into mongoDB Compass and change a user's approved field to 'false' to suspend their account. When a suspended user tries to login, they will get an alert message and will not be able to access their account.

Comment: That's a neat idea, I tried it out:

image

4.
> Updated comments in various files

> Removed unnecessary or commented-out code in various files

Comment: I appreciate you doing this, even though you didn't have to!

**Comment by SaraK207** [comment]
> Looks good. I have a few comments:
> 
> 
> image
> 
> Suggestion: Would it be possible to distinguish a bad link and a bad word and have that reflected in the alert message? For example, if I type in a bad word, it would say "This message contains a bad word and was not sent", and if I type a bad link, it would say "This message contains a bad link and was not sent"? If it's possible, but takes longer than 5 minutes to implement, then there is no need to do this.
> 
I've updated the code to include messages for three cases - 1. Only bad word 2. Only bad link 3. Bad word and Bad link in message
> 
> > For the login/registration pages, user emails were case-sensitive. This means one user could make an account with email "[myemail@gmail.com](mailto:myemail@gmail.com)" and a different user could make an account with email "[MYEMAIL@gmail.com](mailto:MYEMAIL@gmail.com)". Since emails are not supposed to be case sensitive, code was added to convert the email input for login/register to lowercase before storing in database or login validation.
> 
> Comment: That's a good idea.
> 
> 
> > Added functionality to suspend user accounts. When user tries to login, a check will be done to see if the account is approved or not. The admins of the application(us) can go into mongoDB Compass and change a user's approved field to 'false' to suspend their account. When a suspended user tries to login, they will get an alert message and will not be able to access their account.
> 
> Comment: That's a neat idea, I tried it out:
> 
> image
> 
> 
> > Updated comments in various files
> 
> > Removed unnecessary or commented-out code in various files
> 
> Comment: I appreciate you doing this, even though you didn't have to!

**Comment by farfar336** [comment]
> I've updated the code to include messages for three cases - 1. Only bad word 2. Only bad link 3. Bad word and Bad link in message

I've tested it out and these are indeed implemented. Thanks for doing that.

I approve of merging this. Are you okay if I merge it?

**Comment by SaraK207** [comment]
> > I've updated the code to include messages for three cases - 1. Only bad word 2. Only bad link 3. Bad word and Bad link in message
> 
> I've tested it out and these are indeed implemented. Thanks for doing that.
> 
> I approve of merging this. Are you okay if I merge it?

Sure you can go ahead and merge it.

**Pull request merged**
