### PR TITLE
Xudong miao/lobby screen

### PR DESCRIPTION
**Pull request by miaoxudong111**
home and lobby

### CODE REVIEW

**Comment by farfar336** [comment]
I asked Xudong to do a Pull request for both the code for home screen back end and lobby screen back end at the same time.

Home screen back end:
-Logout button directs user to login screen [Button does not respond]
-Lobby button directs the user to the lobby screen [Done]

Lobby screen back end:
-Button to enter active chat directs user to the chat screen [Button does not respond]
-Load the chat names from the DB to the list of chat names displayed [Done]
-Button to create chat directs user to the chat creation screen [Done]
-Button to go to home screen directs the user to the home screen [Done]
-Moderator only: Button to decline 'chat creation' changes the status of that chat from pending to removed, and removes that chat from the screen [Done]
-Moderator only: Button to accept 'chat creation' changes the status of that chat from pending to active [Done]

**Comment by farfar336** [comment]
> Home screen back end:
> -Logout button directs user to login screen [Button does not respond]
> 
> Lobby screen back end:
> -Button to enter active chat directs user to the chat screen [Button does not respond]

The above 2 bullet points have been completed.

I approve of merging this to the main branch.

**Review by SaraK207 — APPROVED** [review]
So it is approving and rejecting chats correctly. However, when displaying chats it is displaying ALL chats in the database and not the ones the current user belongs to. After we pull all chats we need to check whether the displayName exists in that chat and only then put it in the chat list. Currently user sees all chats even if they are not part of it. 

Merge this branch for now and we can do the chat filtering in the next stage.

**Comment by farfar336** [comment]
> So it is approving and rejecting chats correctly. However, when displaying chats it is displaying ALL chats in the database and not the ones the current user belongs to. After we pull all chats we need to check whether the displayName exists in that chat and only then put it in the chat list. Currently user sees all chats even if they are not part of it.
> 
> Merge this branch for now and we can do the chat filtering in the next stage.

The final design of this is as you said, meaning, eventually, we will have users only be shown chats they are part of. For now, I thought it would be easier to just retrieve all the chats. We would implement the functionality of the user being shown only their chats in a future sprint.

I'll merge this right now

**Pull request merged**
